# Docs: https://docs.docker.com/compose/compose-file/
version: '3'
services:
  web:
    image: "node:13-buster-slim"
    volumes:
      - ./:/data
    working_dir: /data
    ports:
      - "3000:3000"
    command: bash -c "yarn && yarn run dev"
    environment:
      HOST: 0.0.0.0
