on:
  create:
    tags:
      - '**'         # When a release is tagged
name: Deploy
jobs:
  production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout tagged release"
      uses: actions/checkout@v2-beta
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@7d6b2b058813e1224cdd4db255b2f163ae4084d3
      env:
        PROJECT: sourcery-prod
        TARGET: tube-1542818590717
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        NODE_ENV: production
      with:
        entrypoint: sh
        args: -c bin/deploy.sh
