on:
  release:
    types: published
name: Deploy to Production
jobs:
  production:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout tagged release"
      uses: actions/checkout@v2-beta
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Node
      uses: actions/setup-node@v1
      env:
        PROJECT: sourcery-prod
        TARGET: tube-1542818590717
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        NODE_ENV: production
      with:
        node-version: '16'
    - run: yarn install --ignore-engines && yarn run generate
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUBE_1542818590717 }}'
        channelId: live
        projectId: tube-1542818590717
        target: tube-1542818590717
