on:
  release:
    types: published
name: Deploy to Production
jobs:
  production:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout tagged release"
      uses: actions/checkout@v2-beta
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.3.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install --ignore-engines && yarn run generate
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@7d6b2b058813e1224cdd4db255b2f163ae4084d3
      env:
        PROJECT: sourcery-prod
        TARGET: tube-1542818590717
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        NODE_ENV: production
      with:
        entrypoint: sh
        args: -c bin/deploy.sh
