on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master # Only run on pushes to master
name: Deploy to Dev
jobs:
  development:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout master branch"
      uses: actions/checkout@v2-beta
      with:
        ref: 'master'
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@7d6b2b058813e1224cdd4db255b2f163ae4084d3
      env:
        PROJECT: sourcery-dev
        TARGET: sourcer-dev
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        entrypoint: sh
        args: -c bin/deploy.sh
