on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master         # Push events on master branch
name: Deploy
jobs:
  branchCheck:
    name: Branch Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@7d6b2b058813e1224cdd4db255b2f163ae4084d3
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        NODE_ENV: production
      with:
        entrypoint: sh
        args: -c bin/deploy.sh
