name: Release

on:
  push:
    branches:
      - feature/supabase-local
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    # Specific to our development version of the web-app and supabase development instance.
    environment: development

    # Required to pass to supabase commands to set as env, and to pre-authenticate to the supabase instance.
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push